In [1]:
# run stopwatch
from _classes import Stopwatch
stopwatch = Stopwatch()
start = stopwatch.start()

### Load Saved Section if exists

if os.path.exists(f'sessions/{dir}'):
    load_session(dir)
else:
    print(f"No such session: 'sessions/{dir}'")

### Load libraries, functions, palette, theme

In [2]:
%run _load.ipynb

In [3]:
economics_data = loadit(
    'economics_data', 'data/00-Datasets/'
)

In [4]:
dir = '003.10_SOL-Purchasing-power'

In [5]:
save_df = 'data/00-Datasets/'

In [6]:
save_excel = 'data/00-Excel-data/'

# <font color='#2C8B6D'>I. Население</font>

# Section III. Уровень жизни

## 3. Доходы, расходы и сбережения населения

### 3.10. Покупательная способность денежных доходов населения, динамические ряды за 2011-2023 годы

*Источник: https://rosstat.gov.ru/folder/13397*  
*Единицы измерения: млрд. руб.*

#### <font color='#2A5899'>Purchasing power</font>

##### Data

In [7]:
purchasing_power_link = \
    ('data/02-Population/02-Standard-of-living/01-Income/'
     'Urov_15kv.xlsx')

In [8]:
purchasing_power_raw = pd.read_excel(purchasing_power_link)

In [9]:
purchasing_power_raw.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Покупательная способность среднедушевых денежн...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,(килограмм),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2011 год,NaN,NaN,NaN,2012 год,NaN,NaN,NaN,2013 год,...,2021 год,NaN,NaN,NaN,2022 год4),NaN,NaN,NaN,2023 год4)6)7),NaN
4,NaN,I квартал,I полугодие,9 месяцев,год,I квартал,I полугодие,9 месяцев,год,I квартал,...,I квартал,I полугодие5),9 месяцев,год,I квартал6),I полугодие6),9 месяцев6),год7),I квартал,I полугодие
5,Говядина (кроме бескостного мяса),"85,2",90,"90,7","94,7","79,7","86,4","89,3","95,2","87,9",...,89,"94,5","97,6",103.9,83.3,89.4,90.9,97,81.4,91.3
6,Свинина (кроме бескостного мяса),"89,2","95,5","97,1","102,3","89,5","96,9",100,"106,7","101,2",...,"119,6","126,3","129,6",138,116.5,129.5,134.3,145.2,130.4,146.3
7,Баранина (кроме бескостного мяса),"78,5","83,3","83,9","87,4","71,1","73,8",75,"79,5","72,1",...,74,"76,9","79,1",84.8,71.9,78.3,79.5,84.8,72.8,80.2
8,Куры охлажденные и мороженые,"170,3","183,6","188,2","200,2",187,"203,3","205,3","214,3",192,...,"209,9","219,4","226,4",238.9,199.9,219,227.1,246.5,228.6,251.7
9,Рыба замороженная (кроме лососевых пород и рыб...,"192,8","203,6","206,7","216,9","187,1","204,7","213,4","229,4","214,3",...,"156,2",167,"174,3",188.6,163.5,177.5,181.9,194.5,164.4,183.5

In [10]:
purchasing_power_raw.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
31,2) В 2014 г. - без учета сведений по Республи...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,3) В расчетах использовались среднедушевые ден...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,4) Без учета статистической информации по Доне...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,5) С 1 полугодия 2021 года расчет квартальных ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,6) Данные уточнены в связи с пересчетом средне...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,7) Предварительные данные.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,8) В 2011 г. г. - молоко питьевое и молочный н...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"9) Масло подсолнечное, килограмм. С 2022 г. - ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,"10) Соль поваренная пищевая, включая йодирован...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,11) Чай черный байховый весовой и чай черный б...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
purchasing_power = purchasing_power_raw.copy()

##### Cut rows and drop NaNs

In [12]:
# cut rows
purchasing_power = transform_cut_rows(purchasing_power, 3, 12)

In [13]:
purchasing_power = transform_fill_values_by_previous(
    purchasing_power, kind='row', row_index=3)

In [14]:
replace_list = ['1)', '2)', '3)', '4)', '5)', '6)', '7)', '8)', '9)', '10)', '11)', ' год']

for column in purchasing_power.columns:
    for i in replace_list:
        purchasing_power[column] = \
            purchasing_power[column].apply(lambda x: transform_replace(x, i, ''))
    purchasing_power[column] = \
        purchasing_power[column].apply(lambda x: transform_replace(x, 'I полугодие', 'II квартал'))
    purchasing_power[column] = \
        purchasing_power[column].apply(lambda x: transform_replace(x, '9 месяцев', 'III квартал'))

In [15]:
purchasing_power.loc[purchasing_power['Unnamed: 0'].isna(), 'Unnamed: 0'] = ['Год', 'Квартал']

In [16]:
# make column as index
purchasing_power = transform_column_as_index(data=purchasing_power, iloc=0)

In [17]:
# make header from two rows
purchasing_power = transform_make_header_from_rows(
    purchasing_power, rows_index=['Год', 'Квартал'])

In [18]:
for column in purchasing_power.columns:
    purchasing_power[column] = \
        purchasing_power[column].apply(lambda x: transform_replace(x, ',', '.'))
    purchasing_power[column] = purchasing_power[column].apply(lambda x: transform_to_float(x))

##### <font color='#2A5899'>Check for Discrepancy: Purchasing power</font>

In [19]:
purchasing_power.isna().any().any()

False

##### <font color='#2A5899'>Final Results: Purchasing power</font>

In [20]:
purchasing_power.head()

                                                        2011             \
                                                   I квартал II квартал
Говядина (кроме бескостного мяса)                       85.2       90.0
Свинина (кроме бескостного мяса)                        89.2       95.5
Баранина (кроме бескостного мяса)                       78.5       83.3
Куры охлажденные и мороженые                           170.3      183.6
Рыба замороженная (кроме лососевых пород и рыбн...     192.8      203.6

                                                                       \
                                                   III квартал    год
Говядина (кроме бескостного мяса)                         90.7   94.7
Свинина (кроме бескостного мяса)                          97.1  102.3
Баранина (кроме бескостного мяса)                         83.9   87.4
Куры охлажденные и мороженые                             188.2  200.2
Рыба замороженная (кроме лососевых пород и рыбн...       206.7  216.9

                                                        2012             \
                                                   I квартал II квартал
Говядина (кроме бескостного мяса)                       79.7       86.4
Свинина (кроме бескостного мяса)                        89.5       96.9
Баранина (кроме бескостного мяса)                       71.1       73.8
Куры охлажденные и мороженые                           187.0      203.3
Рыба замороженная (кроме лососевых пород и рыбн...     187.1      204.7

                                                                       \
                                                   III квартал    год
Говядина (кроме бескостного мяса)                         89.3   95.2
Свинина (кроме бескостного мяса)                         100.0  106.7
Баранина (кроме бескостного мяса)                         75.0   79.5
Куры охлажденные и мороженые                             205.3  214.3
Рыба замороженная (кроме лососевых пород и рыбн...       213.4  229.4

                                                        2013             ...  \
                                                   I квартал II квартал  ...
Говядина (кроме бескостного мяса)                       87.9       94.7  ...
Свинина (кроме бескостного мяса)                       101.2      109.9  ...
Баранина (кроме бескостного мяса)                       72.1       77.5  ...
Куры охлажденные и мороженые                           192.0      209.9  ...
Рыба замороженная (кроме лососевых пород и рыбн...     214.3      229.3  ...

                                                        2021             \
                                                   I квартал II квартал
Говядина (кроме бескостного мяса)                       89.0       94.5
Свинина (кроме бескостного мяса)                       119.6      126.3
Баранина (кроме бескостного мяса)                       74.0       76.9
Куры охлажденные и мороженые                           209.9      219.4
Рыба замороженная (кроме лососевых пород и рыбн...     156.2      167.0

                                                                       \
                                                   III квартал    год
Говядина (кроме бескостного мяса)                         97.6  103.9
Свинина (кроме бескостного мяса)                         129.6  138.0
Баранина (кроме бескостного мяса)                         79.1   84.8
Куры охлажденные и мороженые                             226.4  238.9
Рыба замороженная (кроме лососевых пород и рыбн...       174.3  188.6

                                                        2022             \
                                                   I квартал II квартал
Говядина (кроме бескостного мяса)                       83.3       89.4
Свинина (кроме бескостного мяса)                       116.5      129.5
Баранина (кроме бескостного мяса)                       71.9       78.3
Куры охлажденные и мороженые                           199.9      219.0
Рыба замороженная (кроме лососевых пород и рыбн...     163.5      177.5

                                                                       \
                                                   III квартал    год
Говядина (кроме бескостного мяса)                         90.9   97.0
Свинина (кроме бескостного мяса)                         134.3  145.2
Баранина (кроме бескостного мяса)                         79.5   84.8
Куры охлажденные и мороженые                             227.1  246.5
Рыба замороженная (кроме лососевых пород и рыбн...       181.9  194.5

                                                        2023
                                                   I квартал II квартал
Говядина (кроме бескостного мяса)                       81.4       91.3
Свинина (кроме бескостного мяса)                       130.4      146.3
Баранина (кроме бескостного мяса)                       72.8       80.2
Куры охлажденные и мороженые                           228.6      251.7
Рыба замороженная (кроме лососевых пород и рыбн...     164.4      183.5

[5 rows x 50 columns]

##### <font color='#AF4035'> Export Dataset to Excel

In [21]:
saveit_excel(
    data=purchasing_power,
    filename=dir,
    path=save_excel,
    sheet='Покупательная способность'
)

'Покупательная способность' sheet created if file '01020105-SOL-Purchasing-power.xlsx'

### Save Dataset

In [22]:
economics_data['3.10'] = purchasing_power

In [23]:
saveit(
    file=economics_data,
    name='economics_data',
    dir=save_df
)

File 'economics_data' saved in directory 'data/00-Datasets/'

### Save Session

In [24]:
save_session(dir)

### Execution time

In [25]:
print(f'Execution time: {stopwatch.stop(start)}')

Execution time: 0:00:11